#!/bin/sh
# Wazuh integrator wrapper -> runs custom-shuffle.py with the bundled Python.
WPYTHON_BIN="framework/python/bin/python3"
SCRIPT_PATH_NAME="$0"
DIR_NAME="$(cd $(dirname ${SCRIPT_PATH_NAME}); pwd -P)"
SCRIPT_NAME="$(basename ${SCRIPT_PATH_NAME})"
case ${DIR_NAME} in
    */integrations)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi
        PYTHON_BIN="${WAZUH_PATH}/${WPYTHON_BIN}"
        ;;
    *)
        PYTHON_BIN="python3"
        ;;
esac
"${PYTHON_BIN}" "${DIR_NAME}/${SCRIPT_NAME}.py" "$@"